/**
 * Contains the definitions of the words.
 *
 * !!! IMPORTANT !!!
 * The order of the fields must match the order of the word
 * sequence!
 */

// Change this number to match the number of words you have!
#define NUMBER_OF_FLASH_CARDS  (112)

// Enum for the cards
enum card_t {
	// Insert words (do not include spaces) here:
  aberrant = 0,
  abscond,
  adulaterate,
  aggrandize,
  ameliorate,
  antipathy,
  aquiline,
  ascetic,
  assuage,
  audacious,
  aver,
  banal,
  bandy,
  bluster,
  burgeon,
  buttress,
  calliope,
  commensurate,
  complaisance,
  corroborate,
  culpability,
  decimate,
  defer,
  demotic,
  desiccate,
  diatribe,
  diffident,
  diffuse,
  dint,
  disabuse,
  discrete,
  disinterest,
  dissemble,
  dogma,
  efficacy,
  embellish,
  emetic,
  endemic,
  enervate,
  engender,
  enigma,
  ephemeral,
  equivocal,
  espouse,
  espy,
  eulogy,
  execrable,
  fawn,
  feigned,
  foster,
  garrulous,
  guile,
  harangue,
  heresy,
  hieroglyph,
  homogeneous,
  iconoclast,
  impervious,
  implacable,
  impugn,
  inchoate,
  inroad,
  insipid,
  irascible,
  laconic,
  latency,
  laudable,
  loquacity,
  lucid,
  magnanimity,
  malevolent,
  mawkish,
  misanthrope,
  miser,
  mitigate,
  moil,
  mollify,
  mulct,
  mundane,
  obdurate,
  obviate,
  occlude,
  pedant,
  perennial,
  pinnace,
  placate,
  plenary,
  pragmatic,
  precarious,
  precipitate,
  precursory,
  prevaricate,
  probity,
  profundity,
  propensity,
  propitiate,
  proximity,
  quiescence,
  raiment,
  rarefy,
  repudiate,
  sanction,
  sedition,
  spacious,
  succinct,
  tractable,
  turpitude,
  umbrageous,
  unfettered,
  vindictive,
  vitreous,
  wheedle,
};

// Card Front
char const * const aa_front_line_one[] = {
	// Insert words with quotations around them here (spaces are fine if necessary):	
  "aberrant",
  "abscond",
  "adulaterate",
  "aggrandize",
  "ameliorate",
  "antipathy",
  "aquiline",
  "ascetic",
  "assuage",
  "audacious",
  "aver",
  "banal",
  "bandy",
  "bluster",
  "burgeon",
  "buttress",
  "calliope",
  "commensurate",
  "complaisance",
  "corroborate",
  "culpability",
  "decimate",
  "defer",
  "demotic",
  "desiccate",
  "diatribe",
  "diffident",
  "diffuse",
  "dint",
  "disabuse",
  "discrete",
  "disinterest",
  "dissemble",
  "dogma",
  "efficacy",
  "embellish",
  "emetic",
  "endemic",
  "enervate",
  "engender",
  "enigma",
  "ephemeral",
  "equivocal",
  "espouse",
  "espy",
  "eulogy",
  "execrable",
  "fawn",
  "feigned",
  "foster",
  "garrulous",
  "guile",
  "harangue",
  "heresy",
  "hieroglyph",
  "homogeneous",
  "iconoclast",
  "impervious",
  "implacable",
  "impugn",
  "inchoate",
  "inroad",
  "insipid",
  "irascible",
  "laconic",
  "latency",
  "laudable",
  "loquacity",
  "lucid",
  "magnanimity",
  "malevolent",
  "mawkish",
  "misanthrope",
  "miser",
  "mitigate",
  "moil",
  "mollify",
  "mulct",
  "mundane",
  "obdurate",
  "obviate",
  "occlude",
  "pedant",
  "perennial",
  "pinnace",
  "placate",
  "plenary",
  "pragmatic",
  "precarious",
  "precipitate",
  "precursory",
  "prevaricate",
  "probity",
  "profundity",
  "propensity",
  "propitiate",
  "proximity",
  "quiescence",
  "raiment",
  "rarefy",
  "repudiate",
  "sanction",
  "sedition",
  "spacious",
  "succinct",
  "tractable",
  "turpitude",
  "umbrageous",
  "unfettered",
  "vindictive",
  "vitreous",
  "wheedle",
};

// Card Back
char const * const aa_back_line_one[] = {
	// Insert definitions with quotations around them here:
	// ORDER OF DEFINITIONS IN LIST MUST MATCH ORDER OF WORDS!!
  "different from the usual or normal",
  "to depart secretly and hide",
  "to corrupt or make impure",
  "to make larger or greater in power",
  "to make better improve",
  "dislike hostility extreme opposition or aversion",
  "curved and/or hooked like an eagle's beak",
  "self-denying abstinent austere",
  "to make less severe ease  relieve",
  "bold daring fearless",
  "to declare to be true affirm",
  "trite and overly common",
  "to discuss lightly or glibly; to pass back and forth",
  "to bully; to threaten; to domineer",
  "to sprout or flourish",
  "to reinforce or support",
  "a steam organ; (a musical instrument)",
  "proportional",
  "disposition to please or comply",
  "to confirm verify",
  "guilt responsibility for wrong",
  "to reduce drastically; to destroy a large part of",
  "to show respect or politeness in a submissive way",
  "of or for ordinary people; popular",
  "to dry completely dehydrate",
  "bitter verbal attack",
  "shy lacking confidence",
  "widely spread out",
  "means; effort; force",
  "to free from erroror misconception",
  "individually distinct; consisting of unconnected elements",
  "unbiased; not interested",
  "to pretend disguise one's motives",
  "rigidly fixed in opinion opinionated",
  "effectiveness  efficiency",
  "to ornament; make attractive with decoration or details",
  "something that induces vomiting",
  "belonging to a particular area; inherent",
  "to weaken sap strength from",
  "to produce cause bring out",
  "a puzzle something inexplicable",
  "momentary transient fleeting",
  "ambiguous open to two interpretations",
  "to support or advocate to marry",
  "to see unexpectedly; to suddenly notice",
  "high praise often in public",
  "extremely bad; detestable; abominable",
  "to flatter excessively seek the favor of",
  "pretended",
  "to nourish cultivate promote",
  "very talkative",
  "trickery deception",
  "a ranting writing or speech lecture",
  "an act opposed to established religious orthodoxy",
  "pictorial character",
  "composed of identical parts",
  "one who attacks traditional beliefs",
  "impossible to penetrate; incapable of being affected",
  "inflexible incapable of being pleased",
  "dispute or contradict in an insulting way; to challenge",
  "imperfectly formed or formulated",
  "a hostile invasion; a raid",
  "bland lacking flavour lacking excitement",
  "easily angered",
  "using few words",
  "the condition of being present but hidden",
  "deserving of praise",
  "talkative",
  "clear and  easily understood",
  "generosity",
  "ill-willed;causing evil or harm to others",
  "sentimental; weakly emotional; slightly nauseating",
  "person who hates human beings",
  "person who is extremely stingy",
  "to soften or make milder",
  "to work hard at; to drudge",
  "to calm or make less severe",
  "to defraud; to blackmail; to confiscate",
  "worldly; commonplace",
  "stubborn",
  "to make unnecessary; to anticipate and prevent",
  "to shut block",
  "uninspired boring academic",
  "present throughout the years; persistent",
  "a small boat usually non-motorized",
  "to soothe or pacify",
  "attended by all qualified members",
  "practical moved by facts rather than abstract ideals",
  "uncertain",
  "to cause to happen; to throw down from a height",
  "forerunner predecessor",
  "to lie evade the truth",
  "honesty high-mindedness",
  "depth (usually depth of thought)",
  "inclination tendency",
  "to win over appease",
  "nearness",
  "inactivity stillness",
  "clothing; garments.",
  "to make thinner purer or more refined",
  "to reject as having no authority",
  "permission support; law; penalty",
  "conduct or language inciting rebellion; act of rebellion",
  "having a false appearance of truth; showy",
  "terse brief concise",
  "obedient yielding",
  "inherent baseness depravity",
  "shady; apt to take offense",
  "free unrestrained",
  "spiteful vengeful unforgiving",
  "pertaining to or resembling glass",
  "to influence or entice by flattery",
};
